#!/bin/bash

# Ntando Computer - Render.com Setup Script
# This script prepares the project for deployment to Render.com

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Ntando Computer - Render.com Setup${NC}"
echo -e "${BLUE}=======================================${NC}"

# Function to print colored output
print_status() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    print_error "Please run this script from the project root directory"
    exit 1
fi

# Create backend directory if it doesn't exist
if [ ! -d "backend" ]; then
    print_info "Creating backend directory..."
    mkdir -p backend
fi

# Copy minimal server to main server file
print_info "Setting up backend server..."
cp backend/server-minimal.js backend/server.js 2>/dev/null || {
    print_error "server-minimal.js not found in backend directory"
    exit 1
}

# Install dependencies
print_info "Installing root dependencies..."
npm install --production

print_info "Installing backend dependencies..."
cd backend && npm install --production && cd ..

# Create uploads directory
print_info "Creating uploads directory..."
mkdir -p backend/uploads
mkdir -p logs

# Create environment file
if [ ! -f ".env" ]; then
    print_info "Creating .env file..."
    cat > .env << EOF
NODE_ENV=production
PORT=10000
JWT_SECRET=your-super-secret-jwt-key-change-this
MONGODB_URI=mongodb://localhost:27017/ntando-computer
EOF
    print_warning "Please update the .env file with your actual values"
fi

# Make scripts executable
chmod +x setup-render.sh 2>/dev/null || true
chmod +x scripts/deploy.sh 2>/dev/null || true

# Create render configuration
print_info "Creating Render.com configuration..."
cp render-working.yaml render.yaml

# Create deployment info
cat > RENDER_DEPLOYMENT_INFO.md << EOF
# Render.com Deployment Information

## Service Configuration
- **Name**: ntando-computer
- **Type**: Web Service
- **Runtime**: Node 18
- **Build Command**: npm install && cd backend && npm install
- **Start Command**: node backend/server.js
- **Health Check**: /api/health

## Environment Variables
- NODE_ENV=production
- PORT=10000
- JWT_SECRET=[auto-generated by Render]
- MONGODB_URI=[from MongoDB database]

## Database
- **Name**: ntando-mongodb
- **Type**: MongoDB
- **Plan**: Free

## Storage
- **Mount Path**: /app/backend/uploads
- **Size**: 5 GB

## URLs
- **Main App**: https://ntando-computer.onrender.com
- **API Health**: https://ntando-computer.onrender.com/api/health
- **Dashboard**: https://ntando-computer.onrender.com

## Next Steps
1. Push your code to GitHub
2. Go to render.com and create a new web service
3. Connect your GitHub repository
4. Use the render.yaml configuration
5. Add the MongoDB database
6. Deploy! 🚀
EOF

print_status "Setup completed successfully!"
echo ""
print_info "Files created/updated:"
echo "  - backend/server.js (minimal version)"
echo "  - render.yaml (Render.com configuration)"
echo "  - .env (environment variables)"
echo "  - RENDER_DEPLOYMENT_INFO.md (deployment guide)"
echo ""
print_info "Next steps:"
echo "  1. Push your code to GitHub"
echo "  2. Go to render.com"
echo "  3. Create new web service"
echo "  4. Connect your repository"
echo "  5. Use render.yaml configuration"
echo "  6. Add MongoDB database"
echo "  7. Deploy! 🚀"
echo ""
print_status "Ready for Render.com deployment!"